language: python
python:
  - "3.6"

dist: trusty
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  
# virtualenv: system_site_packages: true

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
