language: python
python:
  - "3.6"

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  
# virtualenv: system_site_packages: true

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
